### ISSUE TITLE
Given alias.

### ISSUE THREAD

**Issue by sunshinejr** [pedrovereza/Brisker#1]
Hey Pedro! This is almost identical to what I'm using lately for Quick, seems like we think alike 😄 Just a quick question, it seems like [here](https://github.com/pedrovereza/Brisk/blob/master/Source/Brisk.swift#L3-L5) you are aliasing `given` to `context` instead of `describe`. Is it a typo or is there a reason for that? 😄

**Comment by pedrovereza** [comment]
Hey @sunshinejr, this tiny project is actually an outcome of https://github.com/Quick/Quick/issues/712 😄 

On using `context` instead of `describe`: no particular reason. In fact, [`context` is basically an alias for `describe`](https://github.com/Quick/Quick/blob/813d9f587baeb79b775c71fe14a5a90681cd9456/Sources/Quick/DSL/World%2BDSL.swift#L37) :wink:

**Comment by sunshinejr** [comment]
Oh, nice! Yeah, I figured, just was curious if there is something else to it 😄 Nvm them, carry on 👍
